- name: create a ec2 instance and records
  hosts: web
  #connection: local
  
  vars:
    instances:
    - mysql
    - backend
    - frontend
    zone: daws81.online
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: subnet-0b3458d1050937273
      instance_type: "t3.micro"
      security_group: sg-0631707908cb6099d
      image_id: ami-0220d79f3f480ecf5
    loop: "{{ instances }}"
    register: ec2_instances
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  - name: creating r53 records
    amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item }}.{{ zone }}"
        type: A
        ttl: 1
        value: "{{ item.instance [0]. private_ip_address }}"
        wait: true
        