- name: create a ec2 instance and records
  hosts: local
  connection: local
  become: yes
  #zone: daws81.online
  vars:
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: subnet-0b3458d1050937273
      instance_type: "t3.micro"
      security_group: sg-0631707908cb6099d
      image_id: ami-0220d79f3f480ecf5
    loop: "{{ instances }}"
    register: ec2-instances
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"


  # - name: Add new.foo.com as an A record with 3 IPs and wait until the changes have been replicated
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{ zone }}"
  #     record: "{{ item.item }}.{{ zone }}"
  #     type: A
  #     ttl: 1
  #     value: "{{ item.instance [0]. private_ip_address }}"
  #     wait: true
        